version: "3.9"

services:
  # ---------- FastAPI / Uvicorn ----------
  api:
    build: .
    command: >
      bash -c "
        playwright install --with-deps &&
        uvicorn main:app --host 0.0.0.0 --port 8000 --proxy-headers
      "
    ports:
      - "8000:8000"
    volumes:
      - ./:/app # live-reload in dev
    env_file: .env
    environment:
      ENV: development
      DEBUG: "true"
      REDIS_URL: redis://redis:6379/0
      PLAYWRIGHT_BROWSERS_PATH: 0 # store browsers inside the container
    depends_on:
      - redis
    restart: unless-stopped

  # ---------- Celery worker -------------
  worker:
    build: .
    command: >
      bash -c "
        playwright install --with-deps &&
        celery -A tasks worker --loglevel=info --concurrency=2
      "
    volumes:
      - ./:/app
    env_file: .env
    environment:
      ENV: development
      DEBUG: "true"
      REDIS_URL: redis://redis:6379/0
      PLAYWRIGHT_BROWSERS_PATH: 0
    depends_on:
      - redis
    restart: unless-stopped

  # ---------- Redis broker --------------
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
